-- CREATE TABLE BARANG (
--     KODEBRG INT PRIMARY KEY,
--     NAMABRG VARCHAR(50)
-- );

-- CREATE TABLE JUAL (
--     KODEBRG INT,
--     JUMLAH INT,
--     FOREIGN KEY (KODEBRG) REFERENCES BARANG(KODEBRG)
-- );

-- INSERT INTO BARANG (KODEBRG, NAMABRG) VALUES
-- (1, 'MEJA'),
-- (2, 'KURSI'),
-- (3, 'LAMPU');

-- INSERT INTO JUAL (KODEBRG, JUMLAH) VALUES
-- (1, 2),
-- (1, 3),
-- (2, 4);

SELECT 	        BARANG.KODEBRG,
				BARANG.NAMABRG,
                COALESCE(SUM(JUAL.JUMLAH), 0) AS JML_JUAL
FROM		    BARANG
LEFT JOIN		JUAL ON BARANG.KODEBRG = JUAL.KODEBRG
GROUP BY		BARANG.KODEBRG, BARANG.NAMABRG
ORDER BY 		KODEBRG ASC



